
import Generic from './../pages/Generic/index';
import {
    HomeOutlined,
    LoginOutlined,
    DatabaseOutlined,
    RetweetOutlined,
    CarOutlined,
    BankOutlined,
    CalculatorOutlined,
    BarcodeOutlined,
    SolutionOutlined,
    DollarOutlined,
    TeamOutlined,
    LogoutOutlined,
    EuroOutlined,
    PrinterOutlined,
    MenuUnfoldOutlined,
    DownSquareOutlined,
    UpSquareOutlined,
    VerticalAlignTopOutlined,
    VerticalAlignBottomOutlined,ExperimentOutlined,
    FireOutlined
} from '@ant-design/icons';
export const documents = [
    {
        key: 1,
        label: 'Приход в банк',
        path: '/documents/bank-arrival',
        Element: <Generic />,
        icon: <LoginOutlined />,
        color: 'red',
        hidden: false,
        private: false,
    },
    {
        key: 2,
        label: 'Расход От Банке',
        path: '/documents/bank-expense',
        Element: <Generic />,
        icon: <LogoutOutlined />,
        color: 'green',
        hidden: false,
        private: false,
    },
    {
        key: 3,
        label: ' Касса приход',
        path: '/documents/cash-register-arrival',
        Element: <Generic />,
        icon: <VerticalAlignBottomOutlined />,
        color: 'blue',
        hidden: false,
        private: false,
    },
    {
        key: 4,
        label: 'Касса Расходы',
        path: '/documents/cash-register-expense',
        Element: <Generic />,
        icon: <VerticalAlignTopOutlined />,
        color: 'violet',
        hidden: false,
        private: false,
    },
    {
        key: 5,
        label: 'Расходы',
        path: '/documents/costs',
        Element: <Generic />,
        icon: <LogoutOutlined />,
        color: '#00f752',
        hidden: false,
        private: false,
    },
    {
        key: 6,
        label: 'Документ поступающий в банк',
        path: '/documents/entering-bank',
        Element: <Generic />,
        icon: <BankOutlined />,
        color: 'blueviolet',
        hidden: false,
        private: false,
    },
    {
        key: 7,
        label: 'Ввот остаток кассы',
        path: '/documents/entering-cash-box',
        Element: <Generic />,
        icon: <CalculatorOutlined />,
        color: '#2fed62',
        hidden: false,
        private: false,
    },
    {
        key: 8,
        label: ' Ввот остаток кредиторы',
        path: '/documents/entering-creditors',
        Element: <Generic />,
        icon: <SolutionOutlined />,
        color: 'blue',
        hidden: false,
        private: false,
    },
    {
        key: 9,
        label: 'Ввот остаток дебиторы',
        path: '/documents/entering-debtors',
        Element: <Generic />,
        icon: <TeamOutlined />,
        color: 'blue',
        hidden: false,
        private: false,
    },
    {
        key: 10,
        label: 'Ввот остаток товара',
        path: '/documents/entering-remainder-goods',
        Element: <Generic />,
        icon: <BarcodeOutlined />,
        color: 'red',
        hidden: false,
        private: false,
    },
    {
        key: 11,
        label: 'Формула производство ',
        path: '/documents/formula-production',
        Element: <Generic />,
        icon: <ExperimentOutlined/>,
        color: 'green',
        hidden: false,
        private: false,
    },
    {
        key: 12,
        label: 'Инвентаризация',
        path: '/documents/inventory',
        Element: <Generic />,
        icon: <MenuUnfoldOutlined />,
        color: 'blueviolet',
        hidden: false,
        private: false,
    },
    {
        key: 13,
        label: 'Перемещение товаров',
        path: '/documents/moving-goods',
        Element: <Generic />,
        icon: <UpSquareOutlined />,
        color: 'aqua',
        hidden: false,
        private: false,
    },
    {
        key: 14,
        label: 'Перемещение денег',
        path: '/documents/moving-money',
        Element: <Generic />,
        icon: <HomeOutlined />,
        color: 'blue',
        hidden: false,
        private: false,
    },
    {
        key: 15,
        label: 'Производство',
        path: '/documents/production',
        Element: <Generic />,
        icon: <PrinterOutlined />,
        color: 'black',
        hidden: false,
        private: false,
    },
    {
        key: 16,
        label: 'Поступление товаров',
        path: '/documents/receipt-of-goods',
        Element: <Generic />,
        icon: <DownSquareOutlined />,
        color: '#00caf7',
        hidden: false,
        private: false,
    },
    {
        key: 17,
        label: 'Возврат товар от килента',
        path: '/documents/return-of-goods-from-the-client',
        Element: <Generic />,
        icon: <RetweetOutlined />,
        color: 'blueviolet',
        hidden: false,
        private: false,
    },
    {
        key: 18,
        label: 'Возврат товар поставщику',
        path: '/documents/return-of-goods-to-the-supplier',
        Element: <Generic />,
        icon: <CarOutlined />,
        color: 'blue',
        hidden: false,
        private: false,
    },
    {
        key: 19,
        label: 'Расчет Зарплаты',
        path: '/documents/salary-calculation',
        Element: <Generic />,
        icon: <EuroOutlined />,
        color: '#f78c00',
        hidden: false,
        private: false,
    },
    {
        key: 20,
        label: 'Тип',
        path: '/documents/type',
        Element: <Generic />,
        icon: <FireOutlined />,
        color: 'red',
        hidden: false,
        private: false,
    },
    {
        key: 21,
        label: 'Оптовые продажи',
        path: '/documents/wholesale',
        Element: <Generic />,
        icon: <DollarOutlined />,
        color: '#f78c00',
        hidden: false,
        private: false,
    },
    {
        key: 22,
        label: 'Списания товаров',
        path: '/documents/write-off-of-goods',
        Element: <Generic />,
        icon: <DatabaseOutlined />,
        color: '#08ff62',
        hidden: false,
        private: false,
    },
]