export const registrs = [
    {
        key: 1,
        label: 'Банк',
        path: '/registrs/bank',
        hidden: false,
        private: false,
    },
    {
        key: 2,
        label: 'Бонус',
        path: '/registrs/bonus',
        hidden: false,
        private: false,
    },
    {
        key: 3,
        label: 'Касса',
        path: '/registrs/cash-box',
        hidden: false,
        private: false,
    },
    {
        key: 4,
        label: 'Расходы',
        path: '/registrs/costs',
        hidden: false,
        private: false,
    },
    {
        key: 5,
        label: 'Валюта',
        path: '/registrs/currency',
        hidden: false,
        private: false,
    },
    {
        key: 6,
        label: 'Товары на складах',
        path: '/registrs/goods-in-ware-houses',
        hidden: false,
        private: false,
    },
    {
        key: 7,
        label: 'Доход',
        path: '/registrs/Income',
        hidden: false,
        private: false,
    },
    {
        key: 8,
        label: 'Взаиморасчеты',
        path: '/registrs/mutual-settlements',
        hidden: false,
        private: false,
    },
    {
        key: 9,
        label: 'Цена номенклатура',
        path: '/registrs/price-nomenclature',
        hidden: false,
        private: false,
    },
    {
        key: 10,
        label: 'Дата погашения',
        path: '/registrs/repayment-date',
        hidden: false,
        private: false,
    },
    {
        key: 11,
        label: 'Продажи',
        path: '/registrs/sales',
        hidden: false,
        private: false,
    },
    {
        key: 12,
        label: 'Расчет с работниками',
        path: '/registrs/settlement-with-workers',
        hidden: false,
        private: false,
    },
]