export const xisobod = [
    {
        key: 1,
        label: 'АКТ Сверка',
        path: '/reports/xisobod',
        hidden: false,
        private: false,
    },
    {
        key: 2,
        label: 'Банк',
        path: '/reports/xisobod',
        hidden: false,
        private: false,
    },
    {
        key: 3,
        label: 'Доходы',
        path: '/reports/xisobod',
        hidden: false,
        private: false,
    },
    {
        key: 4,
        label: 'Касса',
        path: '/reports/xisobod',
        hidden: false,
        private: false,
    },
    {
        key: 5,
        label: 'Кредиторы и дебеторы оборот',
        path: '/reports/xisobod',
        hidden: false,
        private: false,
    },
    {
        key: 6,
        label: 'Кредиторы и дебеторы',
        path: '/reports/xisobod',
        hidden: false,
        private: false,
    },
    {
        key: 7,
        label: 'Сервис',
        path: '/reports/xisobod',
        hidden: false,
        private: false,
    },
    {
        key: 8,
        label: 'Тавар',
        path: '/reports/xisobod',
        hidden: false,
        private: false,
    },
    {
        key: 9,
        label: 'Тавар бнйича хисобот',
        path: '/reports/xisobod',
        hidden: false,
        private: false,
    },
    {
        key: 10,
        label: 'Расходы',
        path: '/reports/xisobod',
        hidden: false,
        private: false,
    },
]